language: node_js
node_js:
- '9'
sudo: required
services:
- docker
before_install:
- docker run -p 6379:6379 -d --name redis redis:3.0.7-alpine
script: NODE_ENV=dev && npm run test:mutation
env:
  global:
    secure: dOtI9r2Ahp9hMfh7Uebz4OkF6jofAaMItpYtR8Ik0Q9NQBgqAA0MssGZqHd3EnClQrO6bBcotATN7YrFvqNuXA156BxsEHxbiM0qcQpcaHIvIoL2cbE0wTp2GiHVFPRS6OqSoL8H6s/Gb3RJVyQ/nQDtjuQgWCJjk9zP7Ma+PiTOokju4Ns283q9npOKaJF8if0JWjypECWygP1KrKi3aBmFssHR2rdUY3LB2W6u9qgSwZT2za24jdUguVD/iyTrCikHQCiwe8zFienWZY1t/kcdb8OEv07EAESACAc3RiMmULWfJ4/PAYN/ZFc8gN1rRdgM8tjabpnG3AHAjHVgJuNzIgFIcswqIIIL/IvEmMBSls0EpPgTsk5rZJXTu9VhEPXzdf2n03kzuq5nyEa0ckn4tPRNVftPfrxp86vrlUaN28f99tZorHHM4QWUex1iO/r7NwgIAklTQodnTcQ1R6AGRdInGKa/xaHPupy2UhUvgKweIQlyYElrC/QspWgxvVy9CtCwuEUV4qzEE3biX1OCQ6yg+HE0/SouL3eUZX3CKFr08wStS+3gU0KahC80srb8jBp4LsWVvLbNZEoMX1AsTy0TeCTgwQvuiUc5Mg2A8ZaEMRILMVdFn/x1c2TuKYerDlaEufhiKHcN/Fup/2Orn0cFgIOLc22SYcVN1Hk=
