language: node_js
node_js:
    - '8'
    - '9'
sudo: required
services:
    - docker
before_install:
    - docker run -p 6379:6379 -d --name redis redis:3.0.7-alpine
script: NODE_ENV=dev && npm run test:mutation